### PR TITLE
Added --list option to print file names

### PR DESCRIPTION
**Pull request by InquisitiveCoder**
I recently rewrote the way MiSTer_SAM handles zip files in order to accommodate a whitelist feature. The new method uses `unzip -Z1` to list the contents of all zip files to stdout. However, [mrchrisster pointed out that unzip will fail for zip files larger than 4 GB]( https://github.com/mrchrisster/MiSTer_SAM/pull/93), so it'd be great if partun had an option for this.

As the commit message points out, I had to update the zip and clap versions to get the build to succeed cleanly. Additionally, the project no longer builds for me on the latest rust nightly due to glibc version mismatches. I had to set rustup to use nightly-2021-06-01 (there's probably other versions that'll work, this one's just the first one that worked for me.) You might have to update your build scripts.

### CODE REVIEW

**Comment by woelper** [comment]
Great - thanks for the PR. I'll review and test tonight and adjust workflow runs if they fail. It's also probably worth trying this out on stable rust.

**Comment by InquisitiveCoder** [comment]
Thanks for the quick reply! I wanted clarify that the glibc version problems I had were specific to the armv7-unknown-linux-gnueabihf build with `cross`. The project still builds using `cargo build` on my PC, and the non-v7 ARM build was also compiling when using `cross`. I'm a complete newbie when it comes to C, Rust, cargo and cross-compilation but I think what's happening is that the glibc version in cross's ARM v7 toolchain on nightly is too recent for bzip2, which zip depends on.

Re: stable Rust, I was able to get `cross` to build on the stable channel if I removed `cargo-features = ["strip"]` and `strip = "symbols"` from Cargo.toml, since those aren't in stable yet. I'm not sure how much of a dealbreaker that would be.

I also got the project building with clap v3 when I was trying to fix the build problems. The changes needed were trivial; the Args constructor changed name and the short name parameter now uses a `char` instead of a string. I figured it was better to keep changes unrelated to the --list option out of this pull request, but I thought you might want to know.

**Comment by woelper** [comment]
Thanks as well!
I am also no `cross` expert - I actually only built this tool for my above mentioned friend mrchrisster and I don't own any ARM hardware apart from an ancient PocketChip. Stripping is just done to make the binary smaller as I believe disk space was an issue.
If this tool is useful for others I am more than happy to do some housekeeping and update/fix the versions of some dependencies and update `clap` as well.

**Review by woelper — APPROVED** [review]

**Comment by woelper** [comment]
Release is done, waiting for mrchrisster to test
https://github.com/woelper/partun/releases/tag/0.1.8

**Pull request merged**
